config/routes.rb
Gmail::Application.routes.draw do

  resources :users, :only => [:create, :new, :show]
  resources :emails
  
  resources :folders
  resources :folderjoins, :only => [:create, :destroy, :update]
  
  resource :session, :only => [:create, :destroy, :new]
  resource :root
  resources :email_processor, :only => [:create]
  
  
  root :to => "roots#show"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password
  attr_reader :password

  has_many :user_folders,
  :class_name => "UserFolder"
  has_many :folder_emails,
  :class_name => "FolderEmail"
  
  has_many :folders, :through => :user_folders, :source => :folder
    
  has_many :sent_emails,
  :class_name => "Email",
  :foreign_key => :sender_address,
  :primary_key => :email
  
  has_many :received_emails,
  :class_name => "Email",
  :foreign_key => :recipient_id

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :email, :presence => true
  validates :email, :uniqueness => true
  validates_format_of :email, :with => /\A(\d|[a-zA-Z])+(\d|[a-zA-Z]|\.)*@gmaily.com/,
  :message => "The first character of your username should be a letter (a-z) or number."

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    loop do
      session_token = SecureRandom::urlsafe_base64(16)
      unless User.find_by_session_token(session_token)
        return session_token
      end
    end
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def create
    params[:user][:email] += '@gmaily.com'
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      7.times { |i|  UserFolder.create(user_id: @user.id, folder_id: i + 1) }
      respond_to do |format|
        format.html { redirect_to root_url } # Entry point into Backbones app
        format.json { render :json => @user }
      end
    else
      flash.now[:errors] = @user.errors.full_messages
      render 'new'
    end
  end

  def new
    @user = User.new
    @user.email = "@gmaily.com"
    render 'new'
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      render :json => "That user doesn't exist!", :status => 422
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form style="margin-left: 10px" role="form" action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <div class="form-inline">
  <input
     class="form-control"
     style="width: 150px"
     id="user_email"
     name="user[email]"
     type="text"
     value="<%= user.email[0..-12] %>"
     placeholder="username">@gmaily.com
  </div>
  <br>
  <div class="form-inline">
  <input
     class="form-control"
     style="width: 150px"
     id="user_password"
     name="user[password]"
     type="password"
     placeholder="password">
  </div>
  <br>
  <input type="submit" class="btn btn-primary" value="<%= message %>">
</form>

app/views/users/new.html.erb
<nav class="navbar navbar-default navbar-fixed-top"
     style="height: 75px;background-color: rgb(241,241,241)">
<form class= "topbar" action="<%= new_session_url %>" method="get">
Have an account? &nbsp; <input type="submit" 
                            value="SIGN IN" 
                            class="btn btn-danger btn-sm"
                            style="font-weight : bold">
</form>
</nav>

<div class="signin-box <%= "has-error" if flash.now[:errors] %>">
<h4>Create User</h4>

<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>

<%= render "form", :user => @user %>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, dear user!</p>